### ISSUE TITLE
GSOC:2018 "Beats: More modules for Metricbeat, Filebeat and Heartbeat"

### ISSUE THREAD

**Issue by Bo0km4n** [elastic/gsoc#19]
Hi I'm Katsuya,
I want to participate GSoC'18, and I'd like to work on Elastic Beats.
I found "Beats: More modules for Metricbeat, Filebeat and Heartbeat" in ideas page.
It's sounds very interesting.
Could you tell me more detail of the issue?

For example about Cassandra module,
should user embed this module in each Cassandra nodes, and this module send the log data to Elasticsearch or ElasticCloud?

**Comment by xeraa** [comment]
Well, it depends a bit: For log files (Filebeat) the Beat normally runs on the same host as the service; otherwise it wouldn't be able to access the relevant files. Mounting files over the network is generally a source of pain I'd try to avoid.

Heartbeat and Metricbeat could either run on the same host or a remote one if the service is reachable over the network.

I'd generally take a look at one of the existing solutions to get a better understanding how they should work. So for example the MySQL module in Metricbeat and Filebeat should give a good overview how stuff could work in Cassandra.

**Comment by xeraa** [comment]
Closing since the application period has finished. We can start a new discussion as needed.
