### ISSUE TITLE
GSOC18 - Project Idea for Heartbeat

### ISSUE THREAD

**Issue by berfinsari** [elastic/gsoc#20]
I am working on contributing to the Heartbeat for traceroute and ping on heartbeat todo page.I contributed to Community Beats by Tracebeat beforehand, We talked that we can [adapt it to the Heartbeat](https://github.com/elastic/beats/pull/5824). I want to participate Google Summer of Code. What do you think about doing this in GSoC?

**Comment by xeraa** [comment]
Nice! Ping @urso @ruflin for input :)

**Comment by ruflin** [comment]
I'm definitively open for a proposal on this. I think we would have to add a bit more "work" to it to make it a full project.

@berfinsari As there is quite a bit of todo around heartbeat we can perhaps combine a few things here?

**Comment by berfinsari** [comment]
I examine Heartbeat todo and requirement list. Add more compression types attracts my attention. Do you have any advice for me such as a reading about it? 
I am going to make it a proposal after examining.

**Comment by ruflin** [comment]
Can you share where you saw the part about more compression types?

**Comment by berfinsari** [comment]
It is located under the http monitor topic in [Heartbeat Todo page.](https://github.com/elastic/beats/blob/master/heartbeat/TODO.md)

**Comment by urso** [comment]
Hi,

Sorry for being late to the discussion. I just returned from vacation.

I think there is quite some potential for loads of work on heartbeat :)

If one checks the commit logs of the heartbeat subdirectory, there wasn't much development on heartbeat since its initial release. Some minor bug fixes and event format overhaul for beats 6.0 release. That is, it does not support some of the newer features found in other beats. For example autodiscovery.

One can check commit history via `git log --stat heartbeat/**/*.go`. Notable commits:
- The initial commit was October 2016: commit ID 614b05e7ef881269f12f75c54bb1c409a33a4162
- Event format overhaul Novenmber 2017: commit ID 6b01fa9dce0273a22e39f93cb72df5e52209e01a
- Monitor code generator: commit ID 192b56587e8361f08b3157c4a30556f23f122d9f

Furthermore the other beats like filebeat, metricbeat, packetbeat, ... are very service oriented. That is, one enbales mysql module to monitor mysql and the module does all the magic. Heartbeat on the other hand is very bare bones. No service oriented monitor types.

So for working on heartbeat only, one could spin a story on widening the scope, but also improve the usability of heartbeat:

- The (original) idea of heartbeat is to monitor a systems, a services, or network health by actively or passively probing those services or devices. => check state of system/service matches expected state => Heartbeat does not generate alerts, but reports the results of each single check.
- As of today heartbeat only supports a small set of monitoring types only.
  - TCP, ICMP ping, HTTP
  - No service discovery (despite, ping all IPs for known DNS name)
- Module reloading differs from other beats => missing integration with auto-discovery
- With ever changing infrastructure and environments + mixed environments, enhanced reloading + auto-discovery is a must. E.g. for integrating heartbeat in k8s environments

=> Project should try to enhance support for different infrastructure + easily usable (curated) list of supported services (e.g. custom protocols)

To figure some of the potential tasks, we have to figure what 'expected state' of a services/network means. Knowing expected state, we can try to figure ways of querying systems/services for that state.
Some ideas:

- Machine/Port/Service available:
  - ICMP ping
  - UDP ping? (Not yet supported by heartbeat)
  - TCP/HTTP can we connect and get response
  - TODO: How many instances of a service are available (e.g. dynamic environments like k8s)
  - TODO: Find services. Right now heartbeat only supports DNS by looking up the address.
    - How about DNS SERVICE support or other lookup mechanisms
    - Redo and integrate heartbeat monitor loading with libbeat autodiscovery support
  - TODO: per monitor customizable DNS lookup/caching (right now the stdlib Resolve function is used)
  - TODO: add optional port scanning support?
  - How about unix socket support?
- Service health:
  - TCP/HTTP check response:
    - How can we improve validation support
  - In case service is behind proxy, how can we enhance support (e.g. ssh tunnel build into heartbeat)
  - Bad/No support for custom protocols/services/device in heartbeat => provide better support for custom protocols and/or implement support for some custom protocols/services:
    - DNS/POP3/FTP/SNMTP/Databases/...
- Network state:
  - IP and MAC address matching (e.g. ARP spoofing)?
    - ARP requests for given local IPs?
    - Query ARP-tables? 
  - DNS tables ok?
  - traceroute: check route of network... Question: Can we integrate traceroute like functionality with every monitor? If so, can we check the traceroute for every packet send when checking a service it's health?
  - (keywords SDN): Routing tables + availability of gateways:
    - BGP or query devices for routing tables?
      - e.g. youtube has been blocked in the past by adding an invalid routing entry via BGP ;)
    - Netconf


Thinking about it, the main themes I could come up with are:
- network state (e.g. traceroute is one of those)
- service discovery
- add support for more services

Maybe you can identify some more themes or tasks. E.g. we're missing Kibana dashboards.

From the TODO you referenced, some of these tasks can be removed. Still relevant (but rather smallish tasks) are:
- ICMP ping on windows
- Add ICMP ping payload
- All HTTP improvements
- TCP improvements
- DNS improvements

Yet, I wouldn't really focus on any of these.

For discussing the final proposal I would suggest to use the forums (as done by others): https://discuss.elastic.co/c/elastic-community/elastic-gsoc

Feel free to start with the proposal and ping @ruflin or me, so we can have a look as well.

**Comment by xeraa** [comment]
Closing since the application period has finished. We can start a new discussion as needed.
