### ISSUE TITLE
Regarding GSoC 2018 Project Proposal

### ISSUE THREAD

**Issue by salekh** [elastic/gsoc#3]
Hallo Devs

I am willing to contribute to the project 'Elasticsearch: Improve Painless's Protection Against Long Scripts' for the Google Summer of Code 2018. Could someone kindly provide shed some light regarding how I should proceed further!

Sincerely
Sanchit

**Comment by xeraa** [comment]
@salekh I'm truly sorry, but we removed that project idea today, since it became kind of outdated since when we created it and now. We'll follow up with more ideas for Elasticsearch really soon.

In the meantime: The most important part of the application process for us is the pull request, so we know that you are comfortable with our toolchain and can make a good contribution.

Sorry once again and you'll have the chance to pick from more challenging projects soon.
