### ISSUE TITLE
Update elasticsearch-lua

### ISSUE THREAD

**Issue by t2013anurag** [elastic/gsoc#4]
I would love to update and add the missing functionalities in the Lua. 

@logmonster  @aravindputrevu Can we connect and discuss further?

**Comment by pmusa** [comment]
Hy @t2013anurag, happy to see your interest and to discuss further.
Are you already using elasticsearch-lua? Do you have any questions?

**Comment by t2013anurag** [comment]
@pmusa  - I came across [elasticsearch-lua](https://github.com/DhavalKapil/elasticsearch-lua/tree/2.x.y/src/elasticsearch) and the [documentation](http://elasticsearch-lua.readthedocs.io/en/latest/)
 
Quick question - 
Is this the repository, we need to work on?
What all features need to be written in Lua script?
Can you refer me to the documentation or the right repo, if the above one is wrong?

**Comment by pmusa** [comment]
> Is this the repository, we need to work on?

Yes, this is the original repo. But you could work on a fork, if you prefer.

> What all features need to be written in Lua script?

Yes, they need. You write a few of them in C, but I am not that is worth it.

**Comment by t2013anurag** [comment]
@pmusa - Thanks, Can you give an example of any such feature which needs to be implemented? This would allow me to familiarize with the codebase real quick.
I will fork the repo and implement on it.

**Comment by SatyendraBanjare** [comment]
Hello @pmusa.... I have successfully Setup ElasticSearch-lua in my system and successfully tested it over elastic 2.4 and it is working just as expected. I when trying with elastic 6.2 it's giving index call errors as explained by Dhaval Kapil here at [link](https://gitter.im/DhavalKapil/elasticsearch-lua). Please tell me on how to proceed further.... :smile:

**Comment by pmusa** [comment]
Sorry @t2013anurag for late response, but we had Elastic{ON} and then team meeting, so I was away for a while. The client update is not only about new features, but about updating what is broken. @SatyendraBanjare had a good example that even indexing a document was not working because starting in ES 5.x you need to provide the content-type in the header. This is one of the examples and you can find many more by looking into the [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking-changes.html) from `5.0` until `6.2`.

**Comment by pmusa** [comment]
> how to proceed further....

My expectation is to have students look into the breaking changes and understand what has changed since `2.x`. Based on that, define potential changes and a timeline to execute them, as recommended in our main page. As stated in the ideas page, we expect a student to have intermediate knowledge about Lua, Elasticsearch, JSON, and HTTP. So, I recommend you show that by creating a pull request.

**Comment by xeraa** [comment]
Closing since the application period has finished. We can start a new discussion as needed.
