### ISSUE TITLE
GSOC 2018 - Kibana: Calendar Visualization and Filtering

### ISSUE THREAD

**Issue by solodynamo** [elastic/gsoc#6]
Hi,
I would like to contribute to Kibana project and take up Calendar Visualization and Filtering idea for the Google Summer of Code 2018. Please guide me towards it.

Thanks,
Ankit Singh
(solodynamo)

**Comment by xeraa** [comment]
There are 2 important parts for every project:

1. The pull request (as described in the readme of the repo), so we know that you are familiar with the toolchain and make a good contribution.
2. A good description of what and how you want to implement it. Since this is a very visual problem, we'd be interested in mockups of what you want to build hinting at the exact features and how to incorporate them into your project.

I hope this helps in getting started :)

**Comment by solodynamo** [comment]
Hey thanks ! will surely update you with the mockups.

**Comment by xeraa** [comment]
Closing since the discussion has shifted to https://discuss.elastic.co/t/regarding-kibana-calendar-visualization-and-filtering/119920/16 (which is also the right place for any other questions around this)
