### ISSUE TITLE
Elasticsearch: Make Painless's Compiler Easier to Understand

### ISSUE THREAD

**Issue by Achint08** [elastic/gsoc#9]
Hello everyone! I am new to this organization. I would love to work on the Project Idea "Elasticsearch: Make Painless's Compiler Easier to Understand". I would like to discuss the project with the mentors and get to know where to start from.

**Comment by xeraa** [comment]
@Achint08 I'm truly sorry, but we removed that project idea today, since it became kind of outdated since when we created it and now. We'll follow up with more ideas for Elasticsearch really soon.

In the meantime: The most important part of the application process for us is the pull request, so we know that you are comfortable with our toolchain and can make a good contribution.

Sorry once again and you'll have the chance to pick from more challenging projects soon.
